# Lab | Pandas

En esta práctica de laboratorio, trabajaremos con los datos del cliente de una compañía de seguros, que se pueden encontrar en el archivo CSV ubicado en el siguiente enlace: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

Los datos incluyen información como identificación del cliente, estado, género, educación, ingresos y otras variables que se pueden utilizar para realizar diversos análisis.

A lo largo del laboratorio, usaremos la biblioteca pandas en Python para manipular y analizar los datos. Pandas es una poderosa biblioteca que proporciona varias herramientas de análisis y manipulación de datos, incluida la capacidad de cargar y manipular datos de una variedad de fuentes, incluidos archivos CSV.

### Data Description

- Client - Client ID

- ST - State where clients live

- Gender - Client gender

- Education - Previous education of clients. 

- Customer Lifetime Value: Customer lifetime value (CLV) is the total revenue that the customer will earn from their entire relationship with a customer. In other words, it is the expected or calculated value of a client during their entire duration as an insured with the insurance company. It is an estimate of the net benefit that the insurance company expects to generate from a client throughout their relationship with the company. Customer lifetime value takes into account factors such as the length of the customer's policy, premium payments, claims history, likelihood of renewal, and potential additional services or products the customer may purchase. It helps insurers evaluate the profitability and long-term value associated with retaining a particular customer.

- Income - Customer income

- Prima Mensual de Auto - Cantidad de dinero que el cliente paga mensualmente como prima por su cobertura de seguro de automóvil. Representa el costo recurrente que el asegurado debe pagar para mantener su póliza de seguro y recibir cobertura por posibles daños, accidentes u otros eventos cubiertos relacionados con su vehículo.

-Número de quejas abiertas - Número de quejas abiertas por el cliente

- Type of policy: there are three types of automobile insurance policies (Corporate Auto, Personal Auto and Special Auto)

- Vehicle class: Type of vehicle classes customers have: two-door car, four-door SUV car, luxury SUV, sports car and luxury car.

-Importe total del reclamo: la suma de todos los reclamos realizados por el cliente. Representa el valor monetario total de todos los reclamos aprobados por incidentes como accidentes, robo, vandalismo u otros eventos cubiertos.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identificar las dimensiones del conjunto de datos determinando el número de filas y columnas que contiene.
- Determinar los tipos de datos de cada columna y evaluar si son apropiados para la naturaleza de la variable. También debe proporcionar sugerencias para corregir cualquier tipo de datos incorrecto.
- Identificar el número de valores únicos para cada columna y determinar qué columnas parecen ser categóricas. También debe describir los valores únicos de cada columna categórica y el rango de valores de las columnas numéricas, y proporcionar comentarios.
- Calcular estadísticas resumidas como media, mediana, moda, desviación estándar y cuartiles para comprender la tendencia central y la distribución de datos en columnas numéricas. También debe proporcionar sus conclusiones basadas en estas estadísticas resumidas.
- Calcule estadísticas resumidas para columnas categóricas y proporcione sus conclusiones basadas en estas estadísticas.

In [2]:
import pandas as pd

In [3]:
url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv'
datos_clientes = pd.read_csv(url)
datos_clientes

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
datos_clientes.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [8]:
datos_clientes.shape

(4008, 11)

In [ ]:
datos_clientes.info()

In [ ]:
# hay 4008 filas en total, pero cada columna tiene 1071 que no son nulos
# GENDER, incluso tiene menos de 1071
#en 'Customer Lifetime Value' los datos estan en str. y tienen un %

In [13]:
datos_clientes.nunique()

Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

In [ ]:
datos_clientes.select_dtypes(include='object')
# las columnas categoricas son : 'Customer, ST, GENDER, Education, Customer Lifetime Value, Number of Open Complaints, Policy Type, Vehicle Class'
# customer lifetime value  deberia ser numerica

C:\Users\Usuario\AppData\Local\Temp\ipykernel_30336\4224002269.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  datos_clientes.select_dtypes(include='object')

,Customer,ST,GENDER,Education,Customer Lifetime Value,Number of Open Complaints,Policy Type,Vehicle Class
0,RB50392,Washington,NaN,Master,NaN,1/0/00,Personal Auto,Four-Door Car
1,QZ44356,Arizona,F,Bachelor,697953.59%,1/0/00,Personal Auto,Four-Door Car
2,AI49188,Nevada,F,Bachelor,1288743.17%,1/0/00,Personal Auto,Two-Door Car
3,WW63253,California,M,Bachelor,764586.18%,1/0/00,Corporate Auto,SUV
4,GA49547,Washington,M,High School or Below,536307.65%,1/0/00,Personal Auto,Four-Door Car
...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
datos_clientes.select_dtypes(include='number')
# las columnas categoricas son : 'Income, Monthly Premium Auto, Total Claim Amount

       Income  Monthly Premium Auto  Total Claim Amount
0         0.0                1000.0            2.704934
1         0.0                  94.0         1131.464935
2     48767.0                 108.0          566.472247
3         0.0                 106.0          529.881344
4     36357.0                  68.0           17.269323
...       ...                   ...                 ...
4003      NaN                   NaN                 NaN
4004      NaN                   NaN                 NaN
4005      NaN                   NaN                 NaN
4006      NaN                   NaN                 NaN
4007      NaN                   NaN                 NaN

[4008 rows x 3 columns]

In [32]:
datos_clientes.describe()
# El valor minimo de income es 0 , pueden ser clientes sin trabajo o dato no recogido
#El valor maximo de MPA es 35354, mientras que el 75% paga 109.5, puede ser un error de toma de datos o error de ingreso de dato
#el valor minimo  en TCA es muy bajo

             Income  Monthly Premium Auto  Total Claim Amount
count   1071.000000           1071.000000         1071.000000
mean   39295.701214            193.234360          404.986909
std    30469.427060           1601.190369          293.027260
min        0.000000             61.000000            0.382107
25%    14072.000000             68.000000          202.157702
50%    36234.000000             83.000000          354.729129
75%    64631.000000            109.500000          532.800000
max    99960.000000          35354.000000         2893.239678

## Challenge 2: analyzing the data

### Exercise 1

El equipo de marketing quiere conocer las cinco ubicaciones de clientes menos comunes. Cree un objeto pandas Series que contenga las ubicaciones de los clientes y sus frecuencias, y luego recupere las 5 ubicaciones menos comunes en orden ascendente.

In [34]:
datos_clientes['ST'].value_counts()
st_clientes = datos_clientes['ST'].value_counts()
st_clientes

ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [ ]:
st_menos_comunes = st_clientes.sort_values() 
st_menos_comunes.head()
st_5menos_comunes = st_menos_comunes.head()
st_5menos_comunes

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

El equipo de ventas quiere saber el número total de pólizas vendidas para cada tipo de póliza. Cree un objeto Pandas Series que contenga los tipos de póliza y su número total de pólizas vendidas, y luego recupere el tipo de póliza con la mayor cantidad de pólizas vendidas.

*Hint:*
- *El uso del método value_counts() simplifica este análisis.*
- *Además, existe un método que devuelve el índice del valor máximo en una columna o fila.*

In [49]:
datos_clientes['Policy Type'].value_counts()
policy_acount = datos_clientes['Policy Type'].value_counts()
print(policy_acount)
policy_acount.idxmax()
max_policy_acount = policy_acount.idxmax()
print(max_policy_acount)

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64
Personal Auto

### Exercise 3

El equipo de ventas quiere saber si los clientes de Auto Personal tienen ingresos más bajos que los de Auto Corporativo. ¿Cómo se compara el ingreso promedio entre los dos tipos de póliza?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [60]:
datos_clientes['Policy Type'] == 'Personal Auto'
clientes_personal_auto = datos_clientes.loc[datos_clientes['Policy Type'] == 'Personal Auto']
media_personal = clientes_personal_auto['Income'].mean()

datos_clientes['Policy Type'] == 'Corporate Auto'
clientes_corporate_auto = datos_clientes.loc[datos_clientes['Policy Type'] == 'Corporate Auto']
media_corporate = clientes_corporate_auto['Income'].mean()

print(media_personal)
print(media_corporate)

38180.69871794872
41390.31196581197

In [65]:
if media_personal < media_corporate:
    print('Personal Auto, tiene una media de ingresos menor')
elif media_personal > media_corporate:
    print('Corporate Auto, tiene una media de ingresos mayor')
else:
    print('ambas son iguales')

Personal Auto, tiene una media de ingresos menor

### Bonus: Exercise 4

Su objetivo es identificar a los clientes con un monto de reclamo de póliza alto.

Instrucciones:

- Revise nuevamente las estadísticas sobre el monto total de la reclamación para comprender los datos.
- Para identificar áreas potenciales para mejorar la retención de clientes y la rentabilidad, queremos centrarnos en clientes con un monto de reclamo de póliza alto. Considere que los clientes con un monto de reclamo de póliza alto son aquellos que se encuentran en el 25% superior del monto total del reclamo. Cree un objeto Pandas DataFrame que contenga información sobre los clientes con un monto de reclamo de póliza superior al percentil 75.
- Utilice métodos DataFrame para calcular estadísticas resumidas sobre los datos de montos elevados de reclamos de pólizas.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [4]:
datos_clientes.describe()

             Income  Monthly Premium Auto  Total Claim Amount
count   1071.000000           1071.000000         1071.000000
mean   39295.701214            193.234360          404.986909
std    30469.427060           1601.190369          293.027260
min        0.000000             61.000000            0.382107
25%    14072.000000             68.000000          202.157702
50%    36234.000000             83.000000          354.729129
75%    64631.000000            109.500000          532.800000
max    99960.000000          35354.000000         2893.239678

In [ ]:
percentil_75 = datos_clientes['Total Claim Amount'].quantile(0.75)
df_tca_high = datos_clientes[datos_clientes['Total Claim Amount'] > percentil_75].copy()
df_tca_high

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
17,OE15005,Cali,NaN,College,394524.16%,28855.0,101.0,1/0/00,Personal Auto,SUV,647.442031
23,TZ98966,Nevada,NaN,Bachelor,245019.10%,0.0,73.0,1/3/00,Corporate Auto,Four-Door Car,554.376763
26,US89481,California,NaN,Bachelor,394637.21%,0.0,111.0,1/0/00,Personal Auto,Four-Door Car,799.200000
...,...,...,...,...,...,...,...,...,...,...,...
1059,YG44474,Oregon,M,College,1401472.13%,54193.0,117.0,1/0/00,Corporate Auto,SUV,720.752945
1061,RY92647,Cali,F,Bachelor,1050677.17%,0.0,92.0,1/0/00,Personal Auto,Four-Door Car,546.524896
1068,GS98873,Arizona,F,Bachelor,323912.47%,16061.0,88.0,1/0/00,Personal Auto,Four-Door Car,633.600000
1069,CW49887,California,F,Master,462680.11%,79487.0,114.0,1/0/00,Special Auto,SUV,547.200000
1070,MY31220,California,F,College,899704.02%,54230.0,112.0,1/0/00,Personal Auto,Two-Door Car,537.600000